In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.groupby('HeartDisease').size()

HeartDisease
0    410
1    508
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [7]:
df.shape

(918, 12)

# ML

In [8]:
mldata=df

In [9]:
mldata

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [10]:
X=mldata.drop('HeartDisease' , axis=1)

In [11]:
y=mldata['HeartDisease']

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [13]:
X_train

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
485,63,M,ATA,139,217,1,ST,128,Y,1.2,Flat
486,55,M,ATA,110,214,1,ST,180,N,0.4,Up
117,59,F,ASY,130,338,1,ST,130,Y,1.5,Flat
361,47,M,ASY,160,0,0,Normal,124,Y,0.0,Flat
296,50,M,ASY,145,0,1,Normal,139,Y,0.7,Flat
...,...,...,...,...,...,...,...,...,...,...,...
276,51,M,NAP,135,160,0,Normal,150,N,2.0,Flat
201,46,M,NAP,120,230,0,Normal,150,N,0.0,Up
462,59,M,ASY,122,233,0,Normal,117,Y,1.3,Down
252,61,M,ASY,125,292,0,ST,115,Y,0.0,Up
62,45,M,ASY,140,224,0,Normal,144,N,0.0,Up

In [14]:
mldata.groupby('ExerciseAngina').size() #Label Encoding will be required

ExerciseAngina
N    547
Y    371
dtype: int64

In [15]:
mldata.groupby('ST_Slope').size() #One hot encoding will be required

ST_Slope
Down     63
Flat    460
Up      395
dtype: int64

In [16]:
mldata.groupby('RestingECG').size() #One hot encoding will be required

RestingECG
LVH       188
Normal    552
ST        178
dtype: int64

In [17]:
mldata.groupby('ChestPainType').size() #One hot encoding will be required

ChestPainType
ASY    496
ATA    173
NAP    203
TA      46
dtype: int64

In [18]:
X_train['ExerciseAngina']=X_train['ExerciseAngina'].map({"N" : 0 , "Y" : 1 })

In [19]:
X_train['Sex']=X_train['Sex'].map({"F" : 0 , "M" : 1 })

In [20]:
X_test['ExerciseAngina']=X_test['ExerciseAngina'].map({"N" : 0 , "Y" : 1 })
X_test['Sex']=X_test['Sex'].map({"F" : 0 , "M" : 1 })

In [21]:
multi_cols = [
    'ST_Slope',
    'RestingECG',
    'ChestPainType'
]

In [22]:
X_train = pd.get_dummies(
    X_train,
    columns=multi_cols,
    drop_first=True,
    dtype=int
)

X_test = pd.get_dummies(
    X_test,
    columns=multi_cols,
    drop_first=True,
    dtype=int
) #One Hot Encoding .

In [23]:
X_train

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope_Flat,ST_Slope_Up,RestingECG_Normal,RestingECG_ST,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
485,63,1,139,217,1,128,1,1.2,1,0,0,1,1,0,0
486,55,1,110,214,1,180,0,0.4,0,1,0,1,1,0,0
117,59,0,130,338,1,130,1,1.5,1,0,0,1,0,0,0
361,47,1,160,0,0,124,1,0.0,1,0,1,0,0,0,0
296,50,1,145,0,1,139,1,0.7,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,51,1,135,160,0,150,0,2.0,1,0,1,0,0,1,0
201,46,1,120,230,0,150,0,0.0,0,1,1,0,0,1,0
462,59,1,122,233,0,117,1,1.3,0,0,1,0,0,0,0
252,61,1,125,292,0,115,1,0.0,0,1,0,1,0,0,0
62,45,1,140,224,0,144,0,0.0,0,1,1,0,0,0,0

# Decision Trees

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
model_DT=DecisionTreeClassifier(random_state=42)

In [26]:
model_DT.fit(X_train , y_train)

DecisionTreeClassifier(random_state=42)

In [27]:
y_pred_DT=model_DT.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [29]:
print(accuracy_score(y_test , y_pred_DT))

0.7663043478260869

In [30]:
print(confusion_matrix(y_test , y_pred_DT))

[[58 24]
 [19 83]]

In [31]:
print(classification_report(y_test , y_pred_DT))

              precision    recall  f1-score   support

           0       0.75      0.71      0.73        82
           1       0.78      0.81      0.79       102

    accuracy                           0.77       184
   macro avg       0.76      0.76      0.76       184
weighted avg       0.77      0.77      0.77       184

# Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

In [33]:
model_NB=GaussianNB()

In [34]:
model_NB.fit(X_train , y_train)

GaussianNB()

In [35]:
y_pred_NB=model_NB.predict(X_test)

In [36]:
print(accuracy_score(y_test , y_pred_NB))

0.9130434782608695

In [37]:
print(confusion_matrix(y_test , y_pred_NB))

[[75  7]
 [ 9 93]]

In [38]:
print(classification_report(y_test , y_pred_DT))

              precision    recall  f1-score   support

           0       0.75      0.71      0.73        82
           1       0.78      0.81      0.79       102

    accuracy                           0.77       184
   macro avg       0.76      0.76      0.76       184
weighted avg       0.77      0.77      0.77       184

# Feature Scaling

In [46]:
list1=['Age' , 'RestingBP' , 'Cholesterol' ,'MaxHR', 'Oldpeak']

In [47]:
X_train_scaled=X_train.copy()
X_test_scaled=X_test.copy()

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [50]:
X_train_scaled[list1]=scaler.fit_transform(X_train_scaled[list1])
X_test_scaled[list1]=scaler.transform(X_test_scaled[list1])

X_train_scaled

# Applying KNN

In [55]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
model_KNN=KNeighborsClassifier(n_neighbors=5)

In [67]:
model_KNN.fit(X_train_scaled , y_train)

KNeighborsClassifier()

In [68]:
y_pred_KNN=model_KNN.predict(X_test_scaled)

In [69]:
print(accuracy_score(y_test , y_pred_KNN))

0.8804347826086957

In [70]:
print(confusion_matrix(y_test , y_pred_KNN)) #y_test-> rows

[[68 14]
 [ 8 94]]

In [71]:
print(classification_report(y_test , y_pred_KNN))

              precision    recall  f1-score   support

           0       0.89      0.83      0.86        82
           1       0.87      0.92      0.90       102

    accuracy                           0.88       184
   macro avg       0.88      0.88      0.88       184
weighted avg       0.88      0.88      0.88       184

# Applying Logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
model_LR=LogisticRegression()

In [72]:
model_LR.fit(X_train_scaled , y_train)

LogisticRegression()

In [73]:
y_pred_LR=model_LR.predict(X_test_scaled)

In [74]:
print(accuracy_score(y_test , y_pred_LR))

0.8858695652173914

In [75]:
print(confusion_matrix(y_test , y_pred_LR)) #y_test-> rows

[[68 14]
 [ 7 95]]

In [76]:
print(classification_report(y_test , y_pred_LR))

              precision    recall  f1-score   support

           0       0.91      0.83      0.87        82
           1       0.87      0.93      0.90       102

    accuracy                           0.89       184
   macro avg       0.89      0.88      0.88       184
weighted avg       0.89      0.89      0.89       184

In [77]:
#Accuracy score : Naive Bayes >LR>KNN>Decision Trees.
# False Negative : Logsitic Regression is best ( only 7)

# SVM

In [78]:
from sklearn.svm import SVC

In [80]:
model_SVM=SVC(kernel='rbf')

In [81]:
model_SVM.fit(X_train_scaled , y_train)

SVC()

In [82]:
y_pred_SVM=model_SVM.predict(X_test_scaled)

In [83]:
accuracy_score(y_pred_SVM , y_test)

0.9021739130434783

In [84]:
print(confusion_matrix(y_pred_SVM , y_test))

[[70  6]
 [12 96]]

In [85]:
print(classification_report(y_pred_SVM , y_test))

              precision    recall  f1-score   support

           0       0.85      0.92      0.89        76
           1       0.94      0.89      0.91       108

    accuracy                           0.90       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.91      0.90      0.90       184

In [ ]:
# 12 False Negative here.